$primary = rgb(e46769)
$surface = rgb(291414)
$secondary = rgb(d6975c)
$error = rgb(c87768)
$tertiary = rgb(cccb66)
$surface_lowest = rgb(150a0a)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
