color0 #291414
color1 #c87768
color2 #e46769
color3 #d6975c
color4 #cccb66
color5 #ec9394
color6 #e9be96
color7 #f3f2f2
color8 #756161
color9 #c87768
color10 #e46769
color11 #d6975c
color12 #cccb66
color13 #ec9394
color14 #e9be96
color15 #f3f2f2

cursor                #f3f2f2
cursor_text_color     #291414
background            #291414
foreground            #f3f2f2
selection_foreground  #b6afaf
selection_background  #371b1b
active_border_color   #e46769
inactive_border_color #371b1b
url_color             #e46769

active_tab_foreground   #251819
active_tab_background   #e46769
inactive_tab_foreground #b6afaf
inactive_tab_background #371b1b
cursor_trail_color      #b6afaf
